### ISSUE TITLE
Post @ChicagoPython Twitter activity in designated Slack channel

### ISSUE THREAD

**Issue by alysivji** [alysivji/busy-beaver#48]
## Task List
- [x] test: can bot post in 2 channels with min amount of permissions
	- Yes
- [x] test: can bot post messages to channel they are not in?
	- Yes
- [x] how to get tweets: api? website?
	- API
- [x] keep track of last seen tweet
	- key-value wrapper around relational database using [simplekv](https://github.com/mbr/simplekv)
- [x] required feature: wait `timedelta` before posting tweet
- [x] create endpoint that kicks off this process
- [x] run with cron, add task to ansible script
- [ ] how to disable bot from posting, keyword in tweet?
	- TODO item.
