### ISSUE TITLE
Integrate redis + python-rq into project

### ISSUE THREAD

**Issue by alysivji** [alysivji/busy-beaver#97]
This is a sub-issue of #76 

## Task List

- [x] dev docker-compose
	- [x] redis container
	- [x] worker container
- [x] integrate flask-rq into web app
	- [x] add to app
	- [x] custom startup script for worker
	- [x] create `Task` model with migration
	- [x] exception handlers
	- [x] create `AsyncException`
- [x] configuration
	- [x] update travis yaml
	- [x] logging
		- [x] add file to log worker container
		- [x] update datadog config
	- [x] sentry
		- [x] rq integration for worker
		- [x] flask integration for web app
		- [x] ensure exception is only counted once
- [x] tests to ensure everything works correctly
- [ ] deployment
	- [x] update env variables on server
	- [x] watchtower has to boot worker in CICD pipeline
	- [x] update docker-compose (worker, redis, env variables, anchors)
	- [ ] rebuild datadog container (this is manual, but we will use docker for logging soon so it's not a big deal)
